# Site settings
title: Design is Refactoring
email: ian@ianwhitney.com
description: "Writing is Rewriting, Designing is Refactoring"
baseurl: ""
url: "http://designisrefactoring.com"
twitter_username: iwhitney
github_username:  IanWhitney

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "vendor", "Gemfile", "Gemfile.lock"]

kramdown:
  input: GFM
  syntax_highlighter: rouge
