title: Design Is Refactoring
email: ian@ianwhitney.com
description: >- # this means to ignore newlines until "baseurl:"
  Writing is Rewriting, Desiging is Refactoring
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://desginisrefactoring.com"
github_username:  IanWhitney
collections:
  newsletters:
    output: true

# Build settings
permalink: pretty
excerpt_separator: <!--break-->
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
